version: 2
updates:
  # Frontend - React + Vite
  - package-ecosystem: "npm"
    directory: "/expense-tracker-web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    assignees:
      - "appi147"

  # Backend - Java + Maven
  - package-ecosystem: "maven"
    directory: "/expense-tracker-rest"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    assignees:
      - "appi147"

  # CI/CD - GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "appi147"
