name: Maven Build Monorepo and Deploy to EC2

permissions:
  contents: read

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: expense-tracker-web/package-lock.json

      - name: Build all Maven modules
        env:
          VITE_API_URL: https://personalexpensetracker.xyz/api
        run: mvn clean package --file pom.xml

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Upload JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ec2_key.pem \
            expense-tracker-rest/target/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIR }}/app.jar

      - name: Restart App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar ${{ secrets.EC2_APP_DIR }}/app.jar > app.log 2>&1 &
          EOF
