name: Deploy Spring Boot Backend

on:
  push:
    branches: [main]
    paths:
      - "expense-tracker-rest/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Build and Deploy JAR
        run: |
          mvn -f expense-tracker-rest/pom.xml clean package
          scp -o StrictHostKeyChecking=no -i ec2_key.pem \
            expense-tracker-rest/target/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIR }}/app.jar

      - name: Restart Backend
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar ${{ secrets.EC2_APP_DIR }}/app.jar > app.log 2>&1 &
          EOF
  sonar-scan:
    name: SonarQube Maven
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expense-tracker-rest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=appi147_ExpenseTracker
