name: Maven Build Monorepo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
