name: Maven Build and Scan

permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: expense-tracker-web/package-lock.json

      - name: Build all Maven modules
        run: mvn clean package --file pom.xml
